sudo: false
language: python

matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 3.4
          env: TOXENV=py34
        - env: TOXENV=pep8

install: pip install tox-travis

script: tox
